apiVersion: v1
kind: Service
metadata:
  name: fitness-api-service
  namespace: fitness-api
  labels:
    app: fitness-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: fitness-api-port
  selector:
    app: fitness-api
  type: ClusterIP