apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fitness-pv-claim
  namespace: fitness-api
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi