apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitness-argo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vinrt/FitnessAPI.git
    targetRevision: HEAD
    path: FitnessAPI
  destination:
    server: https://kubernetes.default.svc
    namespace: test-argocd-ns

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
